#!/usr/bin/env bash
# ==================================================================================================
# DPS Project - Bootstrap NixOS - Deploy VM Action
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Date:          Created: 2025-10-17 | Modified: 2025-10-26
# Description:   Deploy VM management hub setup with deployment tools and infrastructure management
# Feature:       LUKS encryption, SOPS integration, SSH orchestration, mass deployment capabilities
# Author:        DPS Project
# ==================================================================================================

# ----------------------------------------------------------------------------------
# ACTION METADATA
# ----------------------------------------------------------------------------------
# readonly ACTION_VERSION="1.0.0"

# ----------------------------------------------------------------------------------
# ACTION CONFIGURATION
# ----------------------------------------------------------------------------------
# @AI - This is  where the setup setups all its required configuration
action_config() {
    # Create preset
    nds_cfg_preset_create "deploy" \
        --display "Deploy" \
        --priority 60

    # Declare settings (deploy-specific)
    nds_cfg_setting_create GIT_REPO_URL \
        --type url \
        --display "Private Git Repository" \
        --default "https://github.com/user/repo.git"

    nds_cfg_setting_create DEPLOY_SSH_KEY_PATH \
        --type path \
        --display "Deploy SSH Key Path" \
        --default "/root/.ssh/deploy_key"

    nds_cfg_setting_create DEPLOY_TOOLS_PATH \
        --type path \
        --display "Deploy Tools Installation Path" \
        --default "${HOME}/deployTools"

    # Set default values for preset vars (if not already set by env)
    # # Access - Admin user and SSH
    # nds_cfg_set ADMIN_USER "admin"
    # nds_cfg_set SUDO_PASSWORD_REQUIRED true
    # nds_cfg_set SSH_ENABLE true
    # nds_cfg_set SSH_PORT 22
    # nds_cfg_set SSH_USE_KEY true
    # nds_cfg_set SSH_KEY_TYPE "ed25519"
    # nds_cfg_set SSH_KEY_PASSPHRASE false

    # # Network
    # nds_cfg_set NETWORK_METHOD "dhcp"

    # # Disk & Encryption
    # nds_cfg_set ENCRYPTION true
    # nds_cfg_set ENCRYPTION_KEY_METHOD "urandom"
    # nds_cfg_set ENCRYPTION_KEY_LENGTH 64

    # # Boot
    # nds_cfg_set BOOTLOADER "systemd-boot"

    # # Security
    # nds_cfg_set SECURE_BOOT false
    # nds_cfg_set FIREWALL_ENABLE true
    # nds_cfg_set HARDENING_ENABLE true
    # nds_cfg_set FAIL2BAN_ENABLE true

    # Quick Setup
    # nds_cfg_set COUNTRY ""
}

# @AI - Optional function to return fields (similar to deploy_get_active_fields)
# action_config_get_active() {
#     echo "GIT_REPO_URL"
#     echo "DEPLOY_SSH_KEY_PATH"
# }

# @AI - Optional function to validate configuration (similar to deploy_validate_extra)
# action_config_validate() {
#     return 0
# }

# ----------------------------------------------------------------------------------
# GENERATE OVERRIDES
# ----------------------------------------------------------------------------------
action_generate_overrides() {
    local hostname timezone locale keyboard_layout keyboard_variant

    hostname=$(nds_cfg_get "HOSTNAME")
    timezone=$(nds_cfg_get "TIMEZONE")
    locale=$(nds_cfg_get "LOCALE")
    keyboard_layout=$(nds_cfg_get "KEYBOARD_LAYOUT")
    keyboard_variant=$(nds_cfg_get "KEYBOARD_VARIANT")

    cat <<EOF
# NDS Bootstrap Overrides - Generated $(date)
{ config, lib, ... }:
{
  networking.hostName = "$hostname";
  time.timeZone = "$timezone";
  i18n.defaultLocale = "$locale";

  services.xserver.xkb = {
    layout = "$keyboard_layout";
$([ -n "$keyboard_variant" ] && echo "    variant = \"$keyboard_variant\";")
  };
}
EOF
}

# ----------------------------------------------------------------------------------
# GENERATE MAIN CONFIG
# ----------------------------------------------------------------------------------
action_generate_config() {
    local nixos_version
    nixos_version=$(nixos-version | cut -d. -f1-2)

    cat <<EOF
# Generated by NDS Bootstrap - $(date)
{ config, lib, pkgs, ... }:
{
  imports = [
    ./hardware-configuration.nix
    ./nds_overrides.nix
    ./deployVM.nix
  ];

  system.stateVersion = "$nixos_version";
}
EOF
}

# ----------------------------------------------------------------------------------
# MAIN WORKFLOW
# ----------------------------------------------------------------------------------
action_setup() {
    # Set action config paths
    NDS_ACTION_CONFIG_FILE="deployVM.nix"
    NDS_ACTION_CONFIG_SOURCE="$(dirname "$0")/nixosConfiguration/deployVM.nix"

    # Description
    console " ${ACTION_CURRENT_DESCRIPTION}"
    console " This will install a NixOS for managing NixOS nodes and include the following features:"
    console "  • Deployment tools (nixos-anywhere, deploy-rs)"
    console "  • Secrets management (age, sops)"

    nds_askUserToProceed " Ready to begin configuration?" || exit 130

    # Configuration phase - uses all enabled presets from registry
if ! nds_cfg_validate_all; then
    nds_cfg_prompt_errors
    echo prompt done
    exit
    nds_cfg_menu || exit 12  # Let user fix the config interactively
    # Now validate the FIXED config
    if ! nds_cfg_validate_all; then 
        error "Configuration still invalid after changes"
        exit 11
    fi
fi

    # echo 1
    # if ! nds_cfg_validate_all; then
    #     echo 2
    #     nds_cfg_prompt_errors
    #     echo 3
    #     # Configuration validation failed
    #     if ! nds_cfg_validate_all; then exit 11 ; fi
    #     echo 5
    # fi
    # echo 6

    # Optional: Show interactive menu
    # nds_cfg_menu || exit 12
echo 1111111111111111111111
    nds_askUserToProceed "Configuration complete. Ready to install?" || exit 13

    # Pre-install phase
    new_section
    section_header "Pre-Install Preparation"

    step_start "Generating configurations"
    _nds_runtime_ensure_dirs || exit 10
    action_generate_overrides > "$NDS_RUNTIME_DIR/config/nds_overrides.nix"
    action_generate_config > "$NDS_RUNTIME_DIR/config/configuration.nix"
    step_complete "Configurations ready"

    step_start "Preparing secrets"
    _prepare_secrets
    step_complete "Secrets prepared"

    # Call pre-install hook if exists
    type action_pre &>/dev/null && action_pre

    # Partitioning phase
    new_section
    section_header "Disk Partitioning"
    nds_partition_run_from_config || exit 13

    # Install phase
    new_section
    section_header "NixOS Installation"
    install_deploy_vm || exit 14

    # Post-install phase
    new_section
    section_header "Post-Install Setup"
    type action_postInstall &>/dev/null && action_postInstall

    # Completion
    new_section
    _show_secrets_info
    action_show_completion

    console ""
    nds_askUserToProceed "Installation complete. Reboot now?" && reboot
}

# ----------------------------------------------------------------------------------
# HOOKS
# ----------------------------------------------------------------------------------
# action_pre() {

# }

# action_postInstall() {

# }

# ----------------------------------------------------------------------------------
# CUSTOM FUNCTIONS
# ----------------------------------------------------------------------------------
install_deploy_tools() {
    section_header "Installing Deploy Tools"

    local admin_user deploy_tools_src deploy_tools_dest
    admin_user=$(nds_cfg_get "ADMIN_USER")

    local script_dir
    script_dir="$(dirname "$(realpath "$0")")"
    deploy_tools_src="${script_dir}/deployTools"
    deploy_tools_dest=$(nds_cfg_get "DEPLOY_TOOLS_PATH")

    # Expand tilde to actual home path
    deploy_tools_dest="${deploy_tools_dest/#\~//home/${admin_user}}"

    step_start "Copying deploy tools to $deploy_tools_dest"

    if [[ ! -d "$deploy_tools_src" ]]; then
        warn "Deploy tools source not found: $deploy_tools_src"
        return 1
    fi

    # Create destination on mounted filesystem
    local mnt_dest="/mnt${deploy_tools_dest}"
    mkdir -p "$mnt_dest"

    # Copy tools
    if ! cp -r "$deploy_tools_src"/* "$mnt_dest/"; then
        step_fail "Failed to copy deploy tools"
        return 1
    fi

    # Set ownership
    chown -R 1000:1000 "$mnt_dest" 2>/dev/null || true

    step_complete "Deploy tools installed"
    pass "Deploy tools installed to: $deploy_tools_dest"
    return 0
}

# ----------------------------------------------------------------------------------
# COMPLETION MESSAGE
# ----------------------------------------------------------------------------------
action_show_completion() {
    console ""
    console "╭─────────────────────────────────────────────╮"
    console "│  Deploy VM Installation Complete! 🎉        │"
    console "╰─────────────────────────────────────────────╯"
    console ""
    console "Next steps:"
    console "  1. Reboot into installed system"
    console "  2. Login as admin (check secrets for password)"
    console "  3. SSH key will be auto-generated on first boot"
    console "  4. Clone your private repo and begin deploying"
    console ""
}

# ----------------------------------------------------------------------------------
# HELPER FUNCTIONS
# ----------------------------------------------------------------------------------

# Prepare secrets in runtime directory
_prepare_secrets() {
    mkdir -p "$NDS_RUNTIME_DIR/secrets"
    local admin_pass
    if command -v openssl >/dev/null 2>&1; then
        admin_pass=$(openssl rand -base64 16)
    else
        admin_pass=$(head -c 24 /dev/urandom | base64 | tr -d '\n=')
    fi
    echo "$admin_pass" > "$NDS_RUNTIME_DIR/secrets/admin_initial_password.txt"

    if [[ -f /tmp/luks_key.txt ]]; then
        mv /tmp/luks_key.txt "$NDS_RUNTIME_DIR/secrets/"
    fi
    if [[ -f /tmp/luks_key.bin ]]; then
        mv /tmp/luks_key.bin "$NDS_RUNTIME_DIR/secrets/"
    fi

    cat > "$NDS_RUNTIME_DIR/secrets/secrets.env" <<EOF
ADMIN_INITIAL_PASSWORD=$admin_pass
GIT_REPO_URL=$(nds_cfg_get "GIT_REPO_URL")
EOF

    chmod 600 "$NDS_RUNTIME_DIR/secrets/"*
}

# Show secrets backup information
_show_secrets_info() {
    section_header "🔐 Secrets Backup Required"
    console ""
    console "Location: $NDS_RUNTIME_DIR/secrets/"
    console ""
    console "⚠️  CRITICAL: Back up these files before rebooting!"
    console ""

    if [[ -f "$NDS_RUNTIME_DIR/secrets/luks_key.txt" ]]; then
        console "   • Encryption key"
    fi
    console "   • Admin initial password"
    console "   • Environment variables"
    console ""
}

# ----------------------------------------------------------------------------------
# RUNTIME & PARTITION HELPERS
# ----------------------------------------------------------------------------------

_nds_runtime_ensure_dirs() {
    mkdir -p "$NDS_RUNTIME_DIR/config" || return 1
    mkdir -p "$NDS_RUNTIME_DIR/secrets" || return 1
    return 0
}

_nds_partition_select_strategy() {
    local strat
    strat=$(nds_cfg_get_env "PARTITION_STRATEGY" "fast")
    echo "$strat"
}

_nds_partition_run() {
    local strat
    strat=$(_nds_partition_select_strategy)
    case "$strat" in
        fast)
            nds_partition_manual_partition_and_mount || return 1
            ;;
        disko)
            nds_partition_disko_apply || return 1
            ;;
        *)
            error "Unknown PARTITION_STRATEGY: $strat"
            return 1
            ;;
    esac
    return 0
}
