#!/usr/bin/env bash
# ==================================================================================================
# DPS Project - Bootstrap NixOS - A NixOS Deployment System
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Date:          Created: 2026-06-27 | Modified: 2026-06-27
# Description:   Write per-host machine.nix facts into a flake checkout (gitignored)
# Feature:       LUKS UUID for opts — flake eval works without this file on CI
# ==================================================================================================

# Write machine.nix into a host directory inside a cloned flake.
# The flake must already define opts/luks in profile; this only supplies the device UUID.
# Usage: _nixinstall_write_machine_facts "disk" "hostname" "flake_root" "encryption" ["host_dir_rel"]
_nixinstall_write_machine_facts() {
    local disk="$1"
    local hostname="$2"
    local flake_root="$3"
    local use_encryption="${4:-false}"
    local host_dir_rel="${5:-hosts/x86_64-linux}"

    if [[ "$use_encryption" != "true" ]]; then
        debug "Skipping machine.nix — encryption disabled"
        return 0
    fi

    if [[ -z "$flake_root" || ! -d "$flake_root" ]]; then
        warn "Flake root not set or missing — skip machine.nix (set NDS_FLAKE_ROOT)"
        return 0
    fi

    local host_dir="${flake_root}/${host_dir_rel}/${hostname}"
    mkdir -p "$host_dir"
    local luks_part="${disk}2"
    local luks_uuid
    luks_uuid=$(blkid -s UUID -o value "$luks_part" 2>/dev/null || true)

    if [[ -z "$luks_uuid" ]]; then
        error "Could not read LUKS UUID from $luks_part"
    fi

    cat > "$host_dir/machine.nix" << EOF
# Generated by NDS — install-time only, do not commit
{ ... }: {
  opts.nixos.security.luks.device = "/dev/disk/by-uuid/${luks_uuid}";
}
EOF

    log "Wrote machine.nix for ${hostname} (LUKS UUID ${luks_uuid})"
    return 0
}
