#!/usr/bin/env bash
# ==================================================================================================
# NDS - Install bundle quickstart markdown
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Date:          Created: 2026-06-30 | Modified: 2026-07-06
# ==================================================================================================

# Description: Write personalized quick-start markdown from NDS_CTX_* snapshot.
_nds_install_bundle_quickstart() {
    local dest="$1"
    local hostname admin_user ssh_port ssh_pw_auth admin_ssh_key port_opt host_ip
    local encryption use_password use_key key_device key_file
    local remote_unlock remote_net remote_ip remote_port unlock_ip ip_note

    hostname="${NDS_CTX_HOSTNAME:-unknown}"
    admin_user="${NDS_CTX_ADMIN_USER:-admin}"
    ssh_port="${NDS_CTX_SSH_PORT:-22}"
    ssh_pw_auth="${NDS_CTX_SSH_PW_AUTH:-true}"
    admin_ssh_key="${NDS_CTX_ADMIN_SSH_KEY:-}"
    encryption="${NDS_CTX_ENCRYPTION:-}"
    use_password="${NDS_CTX_ENCRYPTION_PASSWORD:-}"
    use_key="${NDS_CTX_ENCRYPTION_KEY:-}"
    key_device="${NDS_CTX_KEY_BOOT_DEVICE:-}"
    key_file="${NDS_CTX_KEY_BOOT_FILE:-}"
    remote_unlock="${NDS_CTX_REMOTE_UNLOCK:-}"
    remote_net="${NDS_CTX_REMOTE_NETWORK:-}"
    remote_ip="${NDS_CTX_NETWORK_IP:-}"
    remote_port="${NDS_CTX_REMOTE_PORT:-2222}"

    # The address this install was reached on - the booted machine gets the same
    # DHCP lease (MAC-based client id), so this is the address to connect to.
    host_ip=$(nds_install_bundle_host_ip 2>/dev/null || true)
    [[ -z "$host_ip" ]] && host_ip="<machine-ip>"

    port_opt=""
    [[ -n "$ssh_port" && "$ssh_port" != "22" ]] && port_opt=" -p ${ssh_port}"

    {
        cat <<EOF
# NDS Quick Start - ${hostname}

Personalized setup guide for this machine, generated by the Nix Deploy System at install
time. **Keep this bundle safe** - it also holds your passwords and unlock secrets.

- **Hostname:** ${hostname}
- **Admin user:** ${admin_user}
- **Address:** ${host_ip}
- **Created:** $(date -Iseconds 2>/dev/null || date)

## What's in this bundle

| Path | What |
|------|------|
| \`nds-config.env\` | Your NDS answers - paste/source before a future NDS run to reuse them |
| \`config/*.nix\` | Generated NixOS config (configuration.nix, hardware-configuration.nix) |
| \`secrets/admin_password.txt\` | Admin user's initial password - **save this** |
| \`logs/install.log\` | Verbose \`nixos-install\` output |
| \`logs/session.log\` | NDS session events (info / warnings / errors) |
EOF

        if [[ "$encryption" == "true" ]]; then
            [[ "$use_password" == "true" ]] && printf '| `secrets/luks_password.txt` | LUKS passphrase - **save this** |\n'
            [[ "$use_key" == "true" ]] && printf '| `secrets/luks_key.bin` | LUKS keyfile - copy to your USB (see below) |\n'
            [[ "$remote_unlock" == "true" ]] && printf '| `secrets/initrd_ssh_host_ed25519_key[.pub]` | initrd SSH host key (remote unlock) |\n'
        fi

        cat <<EOF

## First login

- **Console:** log in as \`${admin_user}\` with the password in \`secrets/admin_password.txt\`.
EOF
        if [[ "$ssh_pw_auth" == "true" || -z "$admin_ssh_key" ]]; then
            cat <<EOF
- **SSH from your PC:**

  \`\`\`bash
  ssh ${admin_user}@${host_ip}${port_opt}
  \`\`\`

  Password login is enabled - use the password above.
EOF
        else
            cat <<EOF
- **SSH from your PC** (key-only - password login is off, use your key):

  \`\`\`bash
  ssh -i <your-private-key> ${admin_user}@${host_ip}${port_opt}
  \`\`\`
EOF
        fi

        cat <<EOF

Change the admin password after first login:

\`\`\`bash
passwd
\`\`\`
EOF

        if [[ "$encryption" == "true" ]]; then
            cat <<EOF

## Disk encryption (LUKS)

This machine's root disk is encrypted - it must be unlocked at every boot.
EOF
            [[ "$use_password" == "true" ]] && \
                printf '\n- **Passphrase:** in `secrets/luks_password.txt`. Type it at the boot/console prompt.\n'

            if [[ "$use_key" == "true" ]]; then
                cat <<EOF

### USB keyfile (required to boot)

The keyfile is in this bundle at \`secrets/luks_key.bin\`. It is **never** written to the
target disk - stage it on a USB stick yourself and plug that USB in at every boot. Its
device path must match:

    ENCRYPTION_KEY_BOOT_DEVICE = ${key_device}
EOF
                if [[ -z "$key_file" ]]; then
                    cat <<EOF

Copy it as **raw bytes** to the USB device (do this BEFORE rebooting):

\`\`\`bash
dd if=secrets/luks_key.bin of=<usb-device> bs=4096 count=1
\`\`\`
EOF
                else
                    cat <<EOF

Copy it as a **file** onto a mounted USB stick (do this BEFORE rebooting):

\`\`\`bash
mount <usb-device> /mnt/usb
cp secrets/luks_key.bin /mnt/usb/${key_file}
umount /mnt/usb
\`\`\`
EOF
                fi

                [[ "$use_password" != "true" ]] && cat <<EOF

> **WARNING - key-only mode (no passphrase).** If this USB is lost, stolen, or corrupted,
> the system **cannot** boot. There is no fallback.
EOF
            fi
        fi

        if [[ "$encryption" == "true" && "$remote_unlock" == "true" ]]; then
            unlock_ip="$host_ip"
            ip_note="DHCP uses a MAC-based client id, so the initrd gets the **same** address as the booted machine (below). If your DHCP server reassigns, check its logs for the lease shown while the LUKS prompt is up."
            if [[ "$remote_net" == "static" && -n "$remote_ip" ]]; then
                unlock_ip="${remote_ip%/*}"
                ip_note="Static IP configured - always reachable at the address below."
            fi

            cat <<EOF

## Remote unlock (initrd SSH)

Before the disk is decrypted, a tiny SSH server runs so you can unlock over the network.

- Listens on **port ${remote_port}** as user **root** (pubkey-only). This differs from the
  system SSH port so the two host keys never clash in known_hosts.
- ${ip_note}
- The initrd host key is in \`secrets/initrd_ssh_host_ed25519_key\`.

Unlock from your PC with the private key whose public key you authorized
(\`nixos-unlock\` in the guide):

\`\`\`bash
# Linux / macOS / WSL
ssh -p ${remote_port} -i ~/.ssh/nixos-unlock root@${unlock_ip}

# Windows (cmd.exe / PowerShell) - use %USERPROFILE%, ~/ is not expanded there
ssh -p ${remote_port} -i "%USERPROFILE%\.ssh\nixos-unlock" root@${unlock_ip}
\`\`\`

The LUKS passphrase prompt appears automatically; type it and the machine boots.

Need to create that key first? On Windows:

\`\`\`bat
ssh-keygen -t ed25519 -f "%USERPROFILE%\.ssh\nixos-unlock"
type "%USERPROFILE%\.ssh\nixos-unlock.pub"
\`\`\`

The safety net is always the **LUKS passphrase** - you can unlock at the physical/VM
console by typing it directly, even if remote access fails.
EOF
        fi

        cat <<EOF

---

Online docs: https://github.com/CodeAnthem/dps_bootstrap
Classic install guide: https://github.com/CodeAnthem/dps_bootstrap/blob/main/actions/classicInstall/README.md
Remote unlock guide: https://github.com/CodeAnthem/dps_bootstrap/blob/main/docs/remote-unlock.md
EOF
    } > "$dest"
}
