#!/usr/bin/env bash
# ==================================================================================================
# NDS - Install backup bundle
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Date:          Created: 2026-06-30 | Modified: 2026-07-02
# Description:   End-of-install zip (config export, generated configs, logs, keys)
# ==================================================================================================

# SSH login user on the live ISO (not root).
nds_install_ssh_user() {
    local user="${SUDO_USER:-nixos}"
    [[ "$user" == root ]] && user=nixos
    printf '%s' "$user"
}

# Best-effort IP the user connected to for copy-paste scp/ssh commands.
nds_install_bundle_host_ip() {
    local host=""
    if [[ -n "${SSH_CONNECTION:-}" ]]; then
        read -r _ _ host _ <<< "$SSH_CONNECTION"
    elif command -v ip &>/dev/null; then
        host=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") print $(i+1); exit}')
    fi
    host="${host:-$(hostname -I 2>/dev/null | awk '{print $1}')}"
    printf '%s' "$host"
}

# Fixed bundle path on the host — a stable name so copy commands never have to
# guess a timestamped filename (good for scripting/automation).
nds_install_bundle_path() {
    local user
    user=$(nds_install_ssh_user)
    printf '/home/%s/nds_bundle.zip' "$user"
}

# Descriptive, timestamped filename for the LOCAL copy on the user's machine —
# keeps a meaningful name once it leaves the host.
nds_install_bundle_local_name() {
    local hostname stamp
    hostname=$(nds_config_get "network" "HOSTNAME" 2>/dev/null || true)
    hostname="${hostname:-nixos}"
    printf -v stamp '%(%Y%m%d_%H%M%S)T' -1
    printf 'nds_install_backup_%s_%s.zip' "$stamp" "$hostname"
}

# Description: Write a personalized quick-start guide into the bundle root. Everything
# the user needs after install for THIS machine - contents, first login, encryption/USB
# staging, and remote unlock - filled in from the live configuration.
# Arguments:
# - dest: <String> Output markdown file path
_nds_install_bundle_quickstart() {
    local dest="$1"
    local hostname admin_user ssh_port ssh_pw_auth admin_ssh_key port_opt host_ip
    local encryption use_password use_key key_device key_file
    local remote_unlock remote_net remote_ip unlock_ip ip_note

    hostname=$(nds_config_get "network" "HOSTNAME" 2>/dev/null || echo unknown)
    admin_user=$(nds_config_get "access" "ADMIN_USER" 2>/dev/null || echo admin)
    ssh_port=$(nds_config_get "access" "SSH_PORT" 2>/dev/null || echo 22)
    ssh_pw_auth=$(nds_config_get "access" "SSH_PASSWORD_AUTH" 2>/dev/null || true)
    admin_ssh_key=$(nds_config_get "access" "ADMIN_SSH_KEY" 2>/dev/null || true)
    encryption=$(nds_config_get "encryption" "ENCRYPTION" 2>/dev/null || true)
    use_password=$(nds_config_get "encryption" "ENCRYPTION_PASSWORD" 2>/dev/null || true)
    use_key=$(nds_config_get "encryption" "ENCRYPTION_KEY" 2>/dev/null || true)
    key_device=$(nds_config_get "encryption" "ENCRYPTION_KEY_BOOT_DEVICE" 2>/dev/null || true)
    key_file=$(nds_config_get "encryption" "ENCRYPTION_KEY_BOOT_FILE" 2>/dev/null || true)
    remote_unlock=$(nds_config_get "encryption" "ENCRYPTION_REMOTE_UNLOCK" 2>/dev/null || true)
    remote_net=$(nds_config_get "encryption" "ENCRYPTION_REMOTE_NETWORK" 2>/dev/null || true)
    remote_ip=$(nds_config_get "network" "NETWORK_IP" 2>/dev/null || true)

    # The address this install was reached on - the booted machine gets the same
    # DHCP lease (MAC-based client id), so this is the address to connect to.
    host_ip=$(nds_install_bundle_host_ip 2>/dev/null || true)
    [[ -z "$host_ip" ]] && host_ip="<machine-ip>"

    port_opt=""
    [[ -n "$ssh_port" && "$ssh_port" != "22" ]] && port_opt=" -p ${ssh_port}"

    {
        cat <<EOF
# NDS Quick Start - ${hostname}

Personalized setup guide for this machine, generated by the Nix Deploy System at install
time. **Keep this bundle safe** - it also holds your passwords and unlock secrets.

- **Hostname:** ${hostname}
- **Admin user:** ${admin_user}
- **Address:** ${host_ip}
- **Created:** $(date -Iseconds 2>/dev/null || date)

## What's in this bundle

| Path | What |
|------|------|
| \`nds-config.env\` | Your NDS answers - paste/source before a future NDS run to reuse them |
| \`config/*.nix\` | Generated NixOS config (configuration.nix, hardware-configuration.nix) |
| \`secrets/admin_password.txt\` | Admin user's initial password - **save this** |
| \`logs/install.log\` | Verbose \`nixos-install\` output |
| \`logs/session.log\` | NDS session events (info / warnings / errors) |
EOF

        if [[ "$encryption" == "true" ]]; then
            [[ "$use_password" == "true" ]] && printf '| `secrets/luks_password.txt` | LUKS passphrase - **save this** |\n'
            [[ "$use_key" == "true" ]] && printf '| `secrets/luks_key.bin` | LUKS keyfile - copy to your USB (see below) |\n'
            [[ "$remote_unlock" == "true" ]] && printf '| `secrets/initrd_ssh_host_ed25519_key[.pub]` | initrd SSH host key (remote unlock) |\n'
        fi

        cat <<EOF

## First login

- **Console:** log in as \`${admin_user}\` with the password in \`secrets/admin_password.txt\`.
EOF
        if [[ "$ssh_pw_auth" == "true" || -z "$admin_ssh_key" ]]; then
            cat <<EOF
- **SSH from your PC:**

  \`\`\`bash
  ssh ${admin_user}@${host_ip}${port_opt}
  \`\`\`

  Password login is enabled - use the password above.
EOF
        else
            cat <<EOF
- **SSH from your PC** (key-only - password login is off, use your key):

  \`\`\`bash
  ssh -i <your-private-key> ${admin_user}@${host_ip}${port_opt}
  \`\`\`
EOF
        fi

        cat <<EOF

Change the admin password after first login:

\`\`\`bash
passwd
\`\`\`
EOF

        if [[ "$encryption" == "true" ]]; then
            cat <<EOF

## Disk encryption (LUKS)

This machine's root disk is encrypted - it must be unlocked at every boot.
EOF
            [[ "$use_password" == "true" ]] && \
                printf '\n- **Passphrase:** in `secrets/luks_password.txt`. Type it at the boot/console prompt.\n'

            if [[ "$use_key" == "true" ]]; then
                cat <<EOF

### USB keyfile (required to boot)

The keyfile is in this bundle at \`secrets/luks_key.bin\`. It is **never** written to the
target disk - stage it on a USB stick yourself and plug that USB in at every boot. Its
device path must match:

    ENCRYPTION_KEY_BOOT_DEVICE = ${key_device}
EOF
                if [[ -z "$key_file" ]]; then
                    cat <<EOF

Copy it as **raw bytes** to the USB device (do this BEFORE rebooting):

\`\`\`bash
dd if=secrets/luks_key.bin of=<usb-device> bs=4096 count=1
\`\`\`
EOF
                else
                    cat <<EOF

Copy it as a **file** onto a mounted USB stick (do this BEFORE rebooting):

\`\`\`bash
mount <usb-device> /mnt/usb
cp secrets/luks_key.bin /mnt/usb/${key_file}
umount /mnt/usb
\`\`\`
EOF
                fi

                [[ "$use_password" != "true" ]] && cat <<EOF

> **WARNING - key-only mode (no passphrase).** If this USB is lost, stolen, or corrupted,
> the system **cannot** boot. There is no fallback.
EOF
            fi
        fi

        if [[ "$encryption" == "true" && "$remote_unlock" == "true" ]]; then
            unlock_ip="$host_ip"
            ip_note="DHCP uses a MAC-based client id, so the initrd gets the **same** address as the booted machine (below). If your DHCP server reassigns, check its logs for the lease shown while the LUKS prompt is up."
            if [[ "$remote_net" == "static" && -n "$remote_ip" ]]; then
                unlock_ip="${remote_ip%/*}"
                ip_note="Static IP configured - always reachable at the address below."
            fi

            cat <<EOF

## Remote unlock (initrd SSH)

Before the disk is decrypted, a tiny SSH server runs so you can unlock over the network.

- Listens on **port 22** as user **root** (pubkey-only).
- ${ip_note}
- The initrd host key is in \`secrets/initrd_ssh_host_ed25519_key\`.

Unlock from your PC with your unlock key (\`~/.ssh/nixos-unlock\` in the guide):

\`\`\`bash
ssh -i ~/.ssh/nixos-unlock root@${unlock_ip}
# the LUKS passphrase prompt appears automatically; type it and the machine boots
\`\`\`

The safety net is always the **LUKS passphrase** - you can unlock at the physical/VM
console by typing it directly, even if remote access fails.
EOF
        fi

        cat <<EOF

---

Online docs: https://github.com/CodeAnthem/dps_bootstrap
Classic install guide: https://github.com/CodeAnthem/dps_bootstrap/blob/main/actions/classicInstall/README.md
Remote unlock guide: https://github.com/CodeAnthem/dps_bootstrap/blob/main/docs/remote-unlock.md
EOF
    } > "$dest"
}

# Create install backup zip in /home/nixos (owned by nixos for scp/ssh copy).
# Sets NDS_INSTALL_BUNDLE. Silent — no prompts.
nds_install_bundle_create() {
    local staging bundle_path user item secret_files=()
    local install_log="${NDS_INSTALL_DETAIL_LOG:-/tmp/nds_install.log}"
    local session_log="${NDS_INSTALL_LOG:-/tmp/nds_session.log}"

    if [[ -n "${NDS_INSTALL_BUNDLE:-}" && -f "$NDS_INSTALL_BUNDLE" ]]; then
        return 0
    fi

    user=$(nds_install_ssh_user)
    bundle_path=$(nds_install_bundle_path)
    staging=$(mktemp -d "${TMPDIR:-/tmp}/nds-bundle-staging.XXXXXX") || return 1

    mkdir -p "${staging}/config" "${staging}/secrets" "${staging}/logs"

    # Config export at the root so it is the first thing the user sees.
    nds_configurator_config_export_script > "${staging}/nds-config.env"

    if [[ -f "${NDS_RUNTIME_DIR:-}/config/configuration.nix" ]]; then
        cp "${NDS_RUNTIME_DIR}/config/configuration.nix" "${staging}/config/"
    fi
    if [[ -f "${NDS_RUNTIME_DIR:-}/config/hardware-configuration.nix" ]]; then
        cp "${NDS_RUNTIME_DIR}/config/hardware-configuration.nix" "${staging}/config/"
    fi

    # Two logs: verbose nix install output and everything else (session events).
    [[ -f "$install_log" ]] && cp "$install_log" "${staging}/logs/install.log"
    [[ -f "$session_log" ]] && cp "$session_log" "${staging}/logs/session.log"

    mapfile -t secret_files < <(nds_secrets_list_runtime)
    for item in "${secret_files[@]}"; do
        [[ -f "$item" ]] && cp "$item" "${staging}/secrets/"
    done

    _nds_install_bundle_quickstart "${staging}/NDS_QUICK_START.md"

    mkdir -p "/home/${user}"
    if command -v zip &>/dev/null; then
        (cd "$staging" && zip -r -q "$bundle_path" .) || {
            rm -rf "$staging"
            error "Failed to create install backup: $bundle_path"
            return 1
        }
    else
        bundle_path="${bundle_path%.zip}.tar.gz"
        tar czf "$bundle_path" -C "$staging" . || {
            rm -rf "$staging"
            error "Failed to create install backup: $bundle_path"
            return 1
        }
    fi
    rm -rf "$staging"

    # Owner only — avoids "invalid group" on live ISOs where the user's group
    # is not named after the user (e.g. nixos → users/nogroup).
    chown "$user" "$bundle_path" 2>/dev/null || true
    chmod 600 "$bundle_path"

    export NDS_INSTALL_BUNDLE="$bundle_path"
    export NDS_SECRETS_BUNDLE="$bundle_path"
    nds_install_log "install backup bundle: $bundle_path"
    return 0
}

# Description: Print a colored line in the given ANSI color (no-op without color).
# Arguments:
# - color: <String> ANSI code (e.g. 32 for green, 35 for magenta, 31 for red)
# - text:  <String> Message
_nds_ui_colored() {
    local color="$1"
    local text="$2"
    nds_ui_init
    if [[ "$NDS_UI_COLOR" == true ]]; then
        printf '%s\033[%sm%s\033[0m\n' "$NDS_UI_INDENT_B" "$color" "$text" >&2
    else
        printf '%s%s\n' "$NDS_UI_INDENT_B" "$text" >&2
    fi
}

_nds_install_bundle_remote_copy_hint() {
    local bundle_path="$1"
    local ssh_user host local_name

    ssh_user=$(nds_install_ssh_user)
    host=$(nds_install_bundle_host_ip)
    [[ -z "$host" ]] && return 0

    # Fixed remote name -> descriptive local name: copy-paste works and still
    # lands a meaningful file on the user's machine.
    local_name=$(nds_install_bundle_local_name)
    [[ "$bundle_path" == *.tar.gz ]] && local_name="${local_name%.zip}.tar.gz"

    nds_ui_b "Backup it from your local machine:"
    nds_ui_i "SCP:"
    nds_ui_i "  scp ${ssh_user}@${host}:${bundle_path} ./${local_name}"
    nds_ui_b ""
    nds_ui_i "SSH:"
    nds_ui_i "  ssh ${ssh_user}@${host} \"cat ${bundle_path}\" > ${local_name}"
    nds_ui_b ""
}

# Description: USB key staging instructions. The keyfile is never written to the
# target disk, so it must be copied onto the USB from the live system BEFORE the
# reboot — this cannot wait for the README. Post-boot help (first login, remote
# unlock) lives in the README instead.
_nds_install_bundle_usbkey_instructions() {
    local encryption use_password use_key key_device key_file
    encryption=$(nds_config_get "encryption" "ENCRYPTION")
    [[ "$encryption" == "true" ]] || return 0

    use_key=$(nds_config_get "encryption" "ENCRYPTION_KEY")
    [[ "$use_key" == "true" ]] || return 0

    use_password=$(nds_config_get "encryption" "ENCRYPTION_PASSWORD")
    key_device=$(nds_config_get "encryption" "ENCRYPTION_KEY_BOOT_DEVICE")
    key_file=$(nds_config_get "encryption" "ENCRYPTION_KEY_BOOT_FILE")

    nds_ui_b ""
    nds_ui_h "Prepare your USB key (required to boot)"
    nds_ui_i "The LUKS key is in this zip at secrets/luks_key.bin."

    if [[ -z "$key_file" ]]; then
        nds_ui_i "Copy it to a USB stick as RAW bytes BEFORE rebooting:"
        nds_ui_i "  dd if=luks_key.bin of=<usb-device> bs=4096 count=1"
        nds_ui_i "Plug that USB in at every boot. Its device path must match:"
        nds_ui_i "  ENCRYPTION_KEY_BOOT_DEVICE = ${key_device}"
    else
        nds_ui_i "Copy it to a file on a USB stick BEFORE rebooting:"
        nds_ui_i "  mount <usb-device> /mnt/usb"
        nds_ui_i "  cp luks_key.bin /mnt/usb/${key_file}"
        nds_ui_i "  umount /mnt/usb"
        nds_ui_i "Plug that USB in at every boot. Its device path must match:"
        nds_ui_i "  ENCRYPTION_KEY_BOOT_DEVICE = ${key_device}"
    fi

    if [[ "$use_password" != "true" ]]; then
        nds_ui_b ""
        _nds_ui_colored 31 "WARNING: key-only mode (no password)."
        _nds_ui_colored 31 "If this USB is lost, stolen, or corrupted, the system CANNOT boot."
        _nds_ui_colored 31 "There is no fallback. Consider re-installing with a password too."
    fi
}

# Post-install screen: backup bundle, copy commands, README pointer, reboot prompt.
nds_install_bundle_finish() {
    local bundle_ok=1
    nds_install_bundle_create || bundle_ok=0

    if [[ "$bundle_ok" -ne 0 && -n "${NDS_INSTALL_BUNDLE:-}" && -f "$NDS_INSTALL_BUNDLE" ]]; then
        section_header "Backup bundle"
        nds_ui_h "Save the restore package for future use"
        nds_ui_b "Copy this zip off the machine before you reboot."
        nds_ui_b "It includes your NDS configuration, install logs, and unlock material (if encrypted)."
        nds_ui_b ""

        if [[ "$(nds_config_get "encryption" "ENCRYPTION")" == "true" ]]; then
            _nds_ui_colored 35 "Encryption was enabled — saving this zip is important."
            _nds_ui_colored 35 "Keep it somewhere safe and offline; it contains your unlock secrets."
            nds_ui_b ""
        fi

        _nds_install_bundle_usbkey_instructions

        _nds_install_bundle_remote_copy_hint "$NDS_INSTALL_BUNDLE"

        nds_askUserToProceed "I have copied the package (or do not need it)" || return 1

        nds_ui_b ""
        nds_ui_h "Next steps"
        nds_ui_b "Personalized first-login and remote-unlock instructions are in the bundle:"
        nds_ui_i "NDS_QUICK_START.md  (at the root of the zip)"
        nds_ui_b "Online guide:"
        nds_ui_i "https://github.com/CodeAnthem/dps_bootstrap/blob/main/actions/classicInstall/README.md"
        nds_ui_b ""
        nds_ui_b "Reboot when ready: sudo reboot"
        nds_askUserToProceed "Reboot now?" && reboot
        return 0
    fi

    # Bundle could not be created — installation still succeeded.
    if [[ "$bundle_ok" -ne 0 ]]; then
        warn "Install backup package could not be created, but installation succeeded."
    fi
    nds_ui_b ""
    nds_ui_b "Reboot when ready: sudo reboot"
    nds_askUserToProceed "Reboot now?" && reboot
    return 0
}

# End-of-install backup bundle and optional reboot.
nds_install_finish() {
    nds_install_bundle_finish || return 1
    return 0
}

# Legacy names (call sites / exports).
nds_secrets_create_bundle() { nds_install_bundle_create "$@"; }
nds_secrets_finish_install() { nds_install_bundle_finish "$@"; }
