#!/usr/bin/env bash
# ==================================================================================================
# NDS - Machine facts writer
# ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Date:          Created: 2026-06-27 | Modified: 2026-06-29
# Description:   Write per-host machine.nix facts into a flake checkout (gitignored)
# ==================================================================================================

# Find LUKS partition UUID (works for nds, disko, and nvme layouts).
# Usage: _nixinstall_find_luks_uuid ["disk"]
_nixinstall_find_luks_uuid() {
    local disk="${1:-}"
    local part uuid backing

    if [[ -e /dev/mapper/cryptroot ]]; then
        backing=$(cryptsetup status cryptroot 2>/dev/null | awk '/device:/ {print $2}')
        if [[ -n "$backing" ]]; then
            uuid=$(blkid -s UUID -o value "$backing" 2>/dev/null || true)
            if [[ -n "$uuid" ]]; then
                echo "$uuid"
                return 0
            fi
        fi
    fi

    if [[ -n "$disk" ]]; then
        for part in "${disk}"*; do
            [[ -b "$part" ]] || continue
            [[ "$(blkid -s TYPE -o value "$part" 2>/dev/null)" == "crypto_LUKS" ]] || continue
            uuid=$(blkid -s UUID -o value "$part" 2>/dev/null || true)
            if [[ -n "$uuid" ]]; then
                echo "$uuid"
                return 0
            fi
        done

        part=$(_nixinstall_disk_part "$disk" 2)
        uuid=$(blkid -s UUID -o value "$part" 2>/dev/null || true)
        if [[ -n "$uuid" ]]; then
            echo "$uuid"
            return 0
        fi
    fi

    return 1
}

# Write machine.nix into a host directory inside a cloned flake.
# Usage: _nixinstall_write_machine_facts "disk" "hostname" "flake_root" "encryption" ["host_dir_rel"]
_nixinstall_write_machine_facts() {
    local disk="$1"
    local hostname="$2"
    local flake_root="$3"
    local use_encryption="${4:-false}"
    local host_dir_rel="${5:-hosts/x86_64-linux}"

    if [[ "$use_encryption" != "true" ]]; then
        debug "Skipping machine.nix — encryption disabled"
        return 0
    fi

    if [[ -z "$flake_root" || ! -d "$flake_root" ]]; then
        warn "Flake root not set or missing — skip machine.nix (set NDS_FLAKE_ROOT)"
        return 0
    fi

    local host_dir="${flake_root}/${host_dir_rel}/${hostname}"
    local luks_uuid
    mkdir -p "$host_dir"

    if ! luks_uuid=$(_nixinstall_find_luks_uuid "$disk"); then
        error "Could not determine LUKS UUID (disk=${disk})"
        return 1
    fi

    cat > "$host_dir/machine.nix" << EOF
# Generated by NDS — install-time only, do not commit
{ ... }: {
  opts.nixos.security.luks.device = "/dev/disk/by-uuid/${luks_uuid}";
}
EOF

    log "Wrote machine.nix for ${hostname} (LUKS UUID ${luks_uuid})"
    nds_install_log "machine.nix written for ${hostname}"
    return 0
}
